version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
